- src/Toml/PrefixTree.hs
- stack-8.0.2.yaml
- stack.yaml
- test/Spec.hs
- test/Test/Toml/PrefixTree.hs
- test/Test/Toml/PrefixTree/Property.hs
- test/Test/Toml/PrefixTree/Unit.hs
- tomland.cabal
Resolves #32 
Implements `InsertLookup` property test for `PrefixTree`. I can't think of more properties for now... Maybe more of them can be discovered in future.
I've also added some unit tests.
> [#32] Add InsertLookup property test for PrefixTree

- CHANGELOG.md
- examples/Playground.hs
- src/Toml/Bi/Combinators.hs
- src/Toml/Edsl.hs
- src/Toml/Type.hs
- tomland.cabal
> [#8] Create EDSL for tomland

- src/Toml/Edsl.hs
`"Oh"` is parsed as a module name.
> Fix Haddock for Toml.Edsl

- CHANGELOG.md
- src/Toml/Parser.hs
- test/Test/Toml/Parsing/Unit.hs
This PR aims to allow underscores in number as mentioned in #17. 
- I've used existing commented out tests and assumed they contain the desired behaviour (the TOML spec doesn't cover some of the edge cases in the commented tests).
- This only works for integers.
- The removing of the underscores is done in a separate action from the parsing. I can use explicit parsers rather than the `match` function, but it's less concise.
- I'm not happy with the use of `undefined` in `fromRight` but the parser should ensure this never happens.
Resolves #17
> [#17] Allow underscores in integers

- CHANGELOG.md
- examples/Playground.hs
- src/Toml/Bi/Combinators.hs
- src/Toml/BiMap.hs
A couple of thoughts:
- I'm not super happy about my modification of `mkAnyValueBiMap`, I couldn't use `prism` since the direction didn't work out, so I ended up using `BiMap`. It works, but it's a bit blunt.
- This PR renders #104 obsolete, probably
- Maybe we need to add comments on `_Show`. Same as the others?
- `stack test` runs fine
Happy to discuss more.
> [Issue #95 ]Reversed BiMap Anything a into BiMap a Anything

- CHANGELOG.md
- src/Toml/Parser.hs
Resolves #22 
The problem is a consequence of typechecking after parsing, using the parser monad. When
the error was produced, as the parser had already consumed the input of the whole array,
the error position was set to the beggining of the next line. A trivial improvement would
be to typecheck before the lexeme parser, which consumes the newline. This way, the error
would be pointed to the end of the array, instead of the next line.
I've implemented a better improvement: to parse the array's elements using the parser that
succeeded to parse the first element. This way, typechecking is done as the array is being
parsed, and type errors are pointed to the exact mismatching element.
A better solution would be to split the parsing and typechecking in two phases. The parser
would preserve …
> [#22] Report proper type checking error during parsing

- src/Toml/Bi/Combinators.hs
- src/Toml/BiMap.hs
- tomland.cabal
I went ahead with #118 since I had most of them ready to go...
- I added the `containers` dependency 
- I made `_Int` because `_IntSet` required it
- I abused the `iso` function for the sets, I know they are not isomorphisms, but it made the definition much sorter
- I haven't changed CHANGELOG yet
> [#118] more container bimaps

- CHANGELOG.md
- src/Toml/Bi/Combinators.hs
- src/Toml/BiMap.hs
- src/Toml/Type/AnyValue.hs
#130 
- I replaced the implementation of `arrayOf ` by simply using `match`. It works, but it seems too simple, am I missing anything?
- Because I've removed the big implementation of `arrayOf`, `matchValueBackward` wasn't needed, so I removed it as well, it felt like it only existed for that purpose. I can bring it back in if needed.
- I'm not sure if we need to keep `dimapNum`, the type casting logic feels like it should stay in `BiMap.hs`
- I re-grouped the exports of `BiMap.hs`
- All tests pass, but we should really add more (related to #119) 
- I really think we should rename `_Array` and `arrayOf` as `_List` and `listOf` since the name reflects the Haskell type (just like with `_Word`), not the way data is stored in the `Anything`
> [#130] Added combinators

- CHANGELOG.md
- src/Toml/Bi/Combinators.hs
- src/Toml/Parser/TOML.hs
- src/Toml/Type/TOML.hs
- test/Test/Toml/Gen.hs
- test/Test/Toml/Parsing/Unit.hs
As title says.
I used `mempty` wherever `tomlTableArrays` was required.
All tests pass.
> [#131] Uncommenting tomlTableArrays

- CHANGELOG.md
- examples/Playground.hs
- src/Toml/Bi/Combinators.hs
- src/Toml/Bi/Monad.hs
Resolves #140 
using `stylish-haskell.yaml` file in the repository.
Start the first line of the commit with the issue number in square parentheses.
> [#140] Change the type of wrapper function

- CHANGELOG.md
- benchmark/Benchmark/Tomland.hs
- benchmark/Benchmark/Type.hs
- benchmark/benchmark.toml
- src/Toml/Parser/Core.hs
- src/Toml/Parser/Value.hs
- test/Test/Toml/Parsing/Unit.hs
Addressing #64 
I re-implemented `decimalP`, it's much simpler now. 
I've uncommented the test on leading zeroes, and modified the `does not parse numbers` tests to actually test failure and not success. To make those pass I had to use the `lookAhead` trick.
While testing these, I realized that the string `"a = 123.3b=23"` is accepted and parsed like `"a = 123.3\nb=23"`. Same for `"a = trueb=23"` and others. It's kind of a weird case, I don't know if it's worth spending time on. Note: `"a = 123b=23"` does not parse because I've used the `lookAhead` trick for integers, so it's definitely fixable.
> [#64] No leading zeros

- CHANGELOG.md
- src/Toml/Parser/Value.hs
- test/Test/Toml/Parsing/Unit.hs
Resolves #129 
using `stylish-haskell.yaml` file in the repository.
Start the first line of the commit with the issue number in square parentheses.
> [#129] Allow underscore in floats

- benchmark/Benchmark/Htoml.hs
- benchmark/Benchmark/HtomlMegaparsec.hs
- benchmark/Benchmark/TomlParser.hs
- benchmark/Benchmark/Tomland.hs
- benchmark/Benchmark/Type.hs
- benchmark/Main.hs
- stack.yaml
- tomland.cabal
Added benchmarks with `toml-parser` library. `tomland` actually is not that fast comparing to other libraries... But, again, we can improve performance later :slightly_smiling_face:
> Add benchmarks with toml-parser library

- test/Test/Toml/BiCode/Property.hs
- test/Test/Toml/BiMap/Property.hs
- test/Test/Toml/Gen.hs
- tomland.cabal
> [#50] Add decode.encode = id tests

- CHANGELOG.md
- cabal.project
- test/Test/Toml/Gen.hs
This PR addresses #177.
This modifies the generator for `Piece` to either generate a bare piece, with alphanumeric and dashes, otherwise it generates either single quoted `''` or double quoted `""` strings containing arbitrary unicode.
All existing tests pass, thankfully.
I've updated the changelog with version 1.0.1, not sure if this is the right one to have there.
> Implement a better generator for `Piece`

- tomland.cabal
Here's how I verified that this worked from the tarball on my machine:
```
$ stack sdist
$ cp .stack-work/dist/x86_64-osx/Cabal-2.4.0.1/tomland-1.0.0.tar.gz ~/scratch/
$ cd ~/scratch/
$ tar -xzf tomland-1.0.0.tar.gz
$ cd tomland-1.0.0
$ edit stack.yaml # see below
$ stack build --test --bench --no-run-benchmarks --fast
```
```yaml
resolver: nightly-2019-02-25
extra-deps:
- htoml-megaparsec-2.1.0.3
- toml-parser-0.1.0.0
- composition-prelude-2.0.2.1
```
> Use extra-source-dirs instead of data-dir, see #141

- CHANGELOG.md
- src/Toml/Parser/Core.hs
- src/Toml/Parser/TOML.hs
- test/Test/Toml/Gen.hs
- test/Test/Toml/Parsing/Unit.hs
- test/Test/Toml/Property.hs
Fixed the exponential behavior, I've had to change a bunch of functions, but in the end it let me refactor `tomlP` nicely so I think it's worth it. Benchmarking also improved.
Since some signatures changed, I've had to modify some tests.
I've also added an `eof` to the TOML parser to make sure the whole `.toml` file is valid.
Benchmarks:
Without fix:
```
benchmarked Parse/tomland
time                 440.8 μs   (430.0 μs .. 453.9 μs)
0.993 R²   (0.989 R² .. 0.997 R²)
mean                 433.0 μs   (427.9 μs .. 440.4 μs)
std dev              20.27 μs   (14.42 μs .. 31.25 μs)
variance introduced by outliers: 27% (moderately inflated)
```
With fix:
```
benchmarked Parse/tomland
time                 355.8 μs   (348.9 μs .. 368.5 μs)
0.990 R²   (0.980 R² .. 0.998 R²)
mean …
```
> [#195] Fix parser exponential behavior

- src/Toml.hs
- src/Toml/Bi/Map.hs
- src/Toml/Bi/Monad.hs
- src/Toml/Generic.hs
- test/Test/Toml/BiCode/Property.hs
- tomland.cabal
Resolves #154
I've come with the implementation of `Generic` codecs. Should help with removing boilerplate. See how it's used in `seaweed`:
* https://github.com/kowainik/seaweed/pull/15
TODO:
> [#154] Implement generic codec

- CHANGELOG.md
- src/Toml/Bi/Combinators.hs
- src/Toml/Bi/Map.hs
- src/Toml/Generic.hs
- src/Toml/Printer.hs
- tomland.cabal
* Bump version to `1.1.0.0` (due to breaking change)
* Add `@since` annotations to new functions
* Write CHANGELOG for the `1.1.0.0` version
> Prepare 1.1.0.0 release

- .gitignore
- stack.yaml
- tomland.cabal
Resolves #209
We can just make a revision on Hackage for this.
> [#209] Bump up parser-combinators to 1.2.0

- .travis.yml
- src/Toml/Parser/Key.hs
- tomland.cabal
Cleanup some metadata:
1. Use `--system-ghc` for `stack` builds.
2. Missing deriving strategies now produce a compiletime error to make sure they are used.
> Cleanup some metadata

- test/Test/Toml/Gen.hs
Fixes half of #198 
We were wondering why you didn't use `genPrefixMap` in `genToml`, seems like the second problem stated in #198 it might be related to `genPrefixMap`, are we on the right path?
Proudly made by @sphaso and @gabrielelana at "Open Source Saturday Milano"
[![Open Source Saturday](https://img.shields.io/badge/%E2%9D%A4%EF%B8%8F-open%20source%20saturday-F64060.svg)](https://www.meetup.com/it-IT/Open-Source-Saturday-Milano/)
> Avoid to generate text with ending backslash

- src/Toml/Parser/Key.hs
Resolves #227
There actually was no problems in the first place! The problem was in a problematic generator in tests (which should be fixed now). The following string for examples parses perfectly:
```haskell
"\n[[a]]\n  \"x\" = []\n"
```
So I just removed redundant code I introduced earlier.
> [#227] Proper newline handling in parser

- test/Test/Toml/Parsing/Unit/Common.hs
- test/Test/Toml/Parsing/Unit/Key.hs
- test/Test/Toml/Parsing/Unit/Toml.hs
Fixes #217. 
This PR is a refactoring of the `Test.Toml.Parsing.Unit.Toml` tests to use the TOML Edsl in the library. 
Sadly I couldn't figure out how to construct the array of arrays as written in the TODO in the code. A lot of time went into wondering whether the Edsl allows array values with more than one property and I couldn't see how. :/
> [#217] Use TOML Edsl, remove redundant utility functions in tests

- CHANGELOG.md
- examples/Main.hs
- examples/biTest.toml
- src/Toml/Bi/Combinators.hs
- test/Test/Toml/BiCode/Property.hs
- tomland.cabal
Resolves #203
This PR implements bidirectional codec for `Map` data structure. I didn't implement it for `HashMap` because it's more boilerplate and it's not apparent how to get rid of it... I've tested it locally and added more tests, and it works!
I think some improvements can be made later once we get a better understanding of what we want. But the current interface seems reasonable to me.
> [#203] Encode / decode Map-like data structures

- tomland.cabal
Resolves #246
I made sure locally that `megaparsec-8.0.0` is used and that the code builds and all tests are passing with `megaparsec-8.0.0`.
> [#246] Bump up to megaparsec-8.0.0

- src/Toml/Generic.hs
- test/Test/Toml/BiCode/Property.hs
First of all, thanks for the great pointers for this PR! A couple of notes:
* This type required a couple more instances of `HasCodec` and `HasItemCodec` for a couple of external types ( Char, ByteString, Map and the various Monoid newtypes ). I've put these as orphan instances in the test file ( as I see was done in the `BiMap` property tests ). But some of them could be added to the `Generic` file as well ( ByteString and Char ), but I thought it would be better to discuss it.
* I had some problems with deriving a generic codec for the `BigTypeSum` and i'm not sure if it's possible to do so. Am I missing something? What I could do is ( since that is the only use case I can think of for a sum type ) is replace the `btSumType` field with a list of `BigSumType` and make the codec like …
> [#202] Add property tests for generic codec

- src/Toml/Codec/BiMap/Conversion.hs
- test/Test/Toml/Codec/BiMap.hs
- test/Test/Toml/Codec/BiMap/Conversion.hs
- test/Test/Toml/Gen.hs
- test/Test/Toml/Type/Key.hs
Resolves #277
For `Category` laws: ideally, those tests should generate random `BiMap` but this is too complicated. So I'm just checking the laws for the specific `TomlBiMap`. I guess this should be enough for now.
> [#277] Fill missing parts in tests

- test/Test/Toml/Parser/Key.hs
Resolves #260
Turned out, the error was a rare case of #198. But I've added more tests on key parsing just in case :slightly_smiling_face:
> [#260] Check on keys starting with "-" parsing

- CHANGELOG.md
- src/Toml/Codec/Code.hs
- src/Toml/Codec/Combinator/Common.hs
- src/Toml/Codec/Combinator/Map.hs
- src/Toml/Codec/Combinator/Table.hs
- src/Toml/Codec/Di.hs
- src/Toml/Codec/Types.hs
> [#311] Reimplement custom State

- CHANGELOG.md
- src/Toml/Codec/Types.hs
- src/Toml/Type/Printer.hs
- test/Test/Toml/Type/Printer.hs
- test/golden/pretty_custom_sorted.golden
- test/golden/pretty_indented_only.golden
- test/golden/pretty_lines.golden
- test/golden/pretty_sorted_only.golden
- test/golden/pretty_unformatted.golden
Resolve #325 
Do we need additional `pretty` function with argument for lines. Or library's users can implement it by self?
Also, for offset I pass through as argument, probably there is better way.
> [#325] Add ptint option for array type

- src/Toml/Parser/Value.hs
- test/Test/Toml/Parser/Integer.hs
According to the issue [#333], tomland has problem with parsing the numbers with leading zero. That problem is some sort of connected with #147 because parser should consume data and throw an error without recovering. 
That feature is now implemented thanks to the ``observing`` function. So if number has leading zero, an error will be thrown, otherwise normal ``more`` parser will be called. It took me some time to figure it out, so any advice how to make this approach better would be appreciated. 
Dario
> Leading zero

- src/Toml/Codec/Combinator.hs
I noticed these are broken links currently https://hackage.haskell.org/package/tomland-1.3.1.0/docs/Toml-Codec-Combinator.html , the module is `Combinator` not `Combinators`.
> Fix doc links to Toml.Codec.Combinator.*

- CHANGELOG.md
- src/Toml/Codec/Code.hs
- src/Toml/Codec/Error.hs
- src/Toml/Type/PrefixTree.hs
- src/Toml/Type/TOML.hs
- test/Test/Toml/Codec/Code.hs
- test/Test/Toml/Codec/Combinator/Common.hs
- test/Test/Toml/Codec/SmallType.hs
Resolves #186
Shout out to @chshersh for pair programming 🙌🏼 ❤️
> [#186] Implement TOML difference

- CHANGELOG.md
- src/Toml/Type/Printer.hs
- stack.yaml
- test/Test/Toml/Type/Printer.hs
- test/golden/pretty_custom_sorted.golden
- test/golden/pretty_default.golden
- test/golden/pretty_indented_only.golden
- test/golden/pretty_lines.golden
- test/golden/pretty_sorted_only.golden
- test/golden/pretty_unformatted.golden
- tomland.cabal
Resolves #368
Also remove `hspec-golden` from dependencies, as it seems to be causing issues with tests after the update.
> [#368] Upgrade hashable lower to 1.3.1.0

- tomland.cabal
https://hackage.haskell.org/package/megaparsec-9.1.0/changelog
> Allow megaparsec 9.1

- cabal.project
- stack.yaml
- tomland.cabal
The `readme` and `play-tomland` executables have very limited usefulness for usual
package users. Therefore it is better to disable them by default in
order to conserve resources.
Additionally, because `build-tool-depends` as used in the `readme`
executable are currently unsupported by Hackage's docs builder,
automated docs builds didn't work for `tomland` and any packages that
depend on it.
Context:
https://github.com/haskell/hackage-server/issues/988#issuecomment-956508617
> Add flags that control building the executables

- tomland.cabal
This matches the revision -r1 already made at
https://hackage.haskell.org/package/tomland-1.3.3.2/revisions/
> Bump bytestring to < 0.13

- tomland.cabal
This will allow the test suite to build with stackage and unblock #443
> Bump hspec-hedgehog to >= 0.0.1.1 && < 0.2

- tomland.cabal
While here also added GHC 9.10.1 to tested-with as it is in CI.
Would be great if we can get a revision or release with this to get `tomland` back in the stackage nightly.
> Bump upper bounds for hashable, megaparsec, hedgehog, and hspec-hedgehog
