- examples/Playground.hs
- src/Toml/Printer.hs
- tomland.cabal
Resolves #4 
I've created `playground` where now you can see the result of printing some example `toml` file. You can `stack exec play-tomland` for that.
Also I didn't touch `tomlTableArrays` for the moment as was discussed.
> [#4] Add basic pretty-printer

- src/Toml/PrefixTree.hs
- tomland.cabal
First attempts of `PrefixTree` (see #29 )
> Add basic PrefixTree

- examples/Playground.hs
- src/Toml/Parser.hs
- src/Toml/PrefixTree.hs
- src/Toml/Printer.hs
- src/Toml/Type.hs
- test.toml
> [#31] Change TOML to use PrefixMap

- examples/Playground.hs
- examples/biTest.toml
- src/Toml.hs
- src/Toml/Bi.hs
- src/Toml/Bi/Combinators.hs
- src/Toml/Bi/Monad.hs
- src/Toml/Parser.hs
- tomland.cabal
Resolves #25 
Implementation is not full. It doesn't support all features. But it works!
What is not implemented:
But this should be relatively easy to add.
> [#25] Implement basic bidirectional Toml conversion

- CHANGELOG.md
- examples/Playground.hs
- examples/biTest.toml
- src/Toml/Bi/Combinators.hs
- src/Toml/Bi/Monad.hs
- src/Toml/Parser.hs
- src/Toml/PrefixTree.hs
- src/Toml/Type.hs
- test.toml
- tomland.cabal
> Make it more usable

- CHANGELOG.md
- examples/Playground.hs
- src/Toml.hs
- src/Toml/Bi/Combinators.hs
> [#44] Add bidirectional converter for Maybe

- CHANGELOG.md
- examples/Playground.hs
- src/Toml/Bi/Combinators.hs
- src/Toml/Bi/Monad.hs
- tomland.cabal
> [#47] Introduce mdimap combinator

- CHANGELOG.md
- examples/Playground.hs
- examples/biTest.toml
- src/Toml/Bi/Combinators.hs
> [#37] Add table support to bi

- CHANGELOG.md
- examples/Playground.hs
- examples/biTest.toml
- src/Toml/Bi.hs
- src/Toml/Bi/Code.hs
- src/Toml/Bi/Combinators.hs
- src/Toml/PrefixTree.hs
- src/Toml/Type.hs
- tomland.cabal
> [#39] Pretty exceptions

- .travis.yml
- stack-8.4.2.yaml
> [#24] Test with GHC-8.4.2 on Travis CI

- CHANGELOG.md
- src/Toml/Bi/Code.hs
- src/Toml/Bi/Combinators.hs
- src/Toml/Edsl.hs
- src/Toml/PrefixTree.hs
- src/Toml/Type.hs
- test/Test/Toml/PrefixTree/Property.hs
- test/Test/Toml/Property.hs
- test/Test/Toml/TOML/Property.hs
- tomland.cabal
[WIP] monoid and semigroup property tests are going to be done in here.
Resolves #10
> [#10] Add Semigroup and Monoid instances TOML

- src/Toml/Parser.hs
Resolves #20 
It would have been better if [Megaparsec](https://github.com/mrkkrp/megaparsec) had support for `binDigitChar` in the same way it supports: ([digitChar](https://hackage.haskell.org/package/megaparsec-6.5.0/docs/Text-Megaparsec-Char.html#v:digitChar), [octDigitChar](https://hackage.haskell.org/package/megaparsec-6.5.0/docs/Text-Megaparsec-Char.html#v:octDigitChar), [hexDigitChar](https://hackage.haskell.org/package/megaparsec-6.5.0/docs/Text-Megaparsec-Char.html#v:hexDigitChar)), and supported `binary` in the same way it supports: ([decimal](https://hackage.haskell.org/package/megaparsec-6.5.0/docs/Text-Megaparsec-Char-Lexer.html#v:decimal), [octal](https://hackage.haskell.org/package/megaparsec-6.5.0/docs/Text-Megaparsec-Char-Lexer.html#v:octal), …
> [#20] Add parsing of hex, oct and bin integers

- CHANGELOG.md
- examples/Playground.hs
- src/Toml.hs
- src/Toml/Bi/Combinators.hs
- src/Toml/Prism.hs
- src/Toml/Type.hs
- tomland.cabal
Resolves #60 
I don't like `unsafeArray` part. But can't do nothing with it.
> [#60] Replace Valuer with Prism

- CHANGELOG.md
- src/Toml/Parser.hs
- src/Toml/Type.hs
- stack-8.0.2.yaml
- test/Test/Toml/Parsing/Unit.hs
- tomland.cabal
Resolves #26 
Tests are implemented for parsing the following types:
- `Integer`
- `Boolean`
- `Array`
> [#26] Implement unit testing for TOML parsing

- CHANGELOG.md
- src/Toml/Parser.hs
- test/Test/Toml/Parsing/Unit.hs
Resolves #19 except for supporting underscores, which I think should be supported after resolving #17.
> [#19] Add proper parsing of floating point numbers

- .travis.yml
- stack-8.0.2.yaml
- stack-8.4.2.yaml
- stack.yaml
- tomland.cabal
> [#23] Use cabal on travis, upgrade to lts-12.0

- CHANGELOG.md
- src/Toml/Parser.hs
- test/Test/Toml/Parsing/Unit.hs
> [#40] Support full-featured string parser

- src/Toml/Bi/Code.hs
- src/Toml/Bi/Combinators.hs
- src/Toml/Bi/Monad.hs
- tomland.cabal
This is a first step towards supporting sum types. Not sure that I'm moving in the right direction... What I want is to have `Alternative` instance for `Bijection`.
> Add `Alternative` instance for `Bijection`

- CHANGELOG.md
- src/Toml/Parser.hs
- stack.yaml
- test/Test/Toml/Parsing/Unit.hs
> [#18] Add dates parsing

- CHANGELOG.md
- src/Toml/Bi/Code.hs
> [#58] Add decodeFile function

- src/Toml/Bi/Combinators.hs
- src/Toml/Bi/Monad.hs
- src/Toml/Prism.hs
This PR just introduces some functions. It's very small. I still don't have full vision of how sum types should be implemented. But I'm slightly moving in this direction.
> Minor refactoring in preparation for sum types

- CHANGELOG.md
- src/Toml/Printer.hs
- stack.yaml
- test/Test/Toml/Gen.hs
- tomland.cabal
Resolves [#85](https://github.com/kowainik/tomland/issues/85)
> [#85] Add date test generator

- .travis.yml
- CHANGELOG.md
- src/Toml/Parser.hs
- test/Test/Toml/Gen.hs
- tomland.cabal
Resolves [#88](https://github.com/kowainik/tomland/issues/88)
> [#88] Add Array test generator

- .travis.yml
- CHANGELOG.md
- test/Test/Toml/Gen.hs
- test/Test/Toml/Parsing/Unit.hs
- tomland.cabal
Resolves [#86](https://github.com/kowainik/tomland/issues/86)
> [#86] Improve String generator

- CHANGELOG.md
- src/Toml/Printer.hs
- src/Toml/Type/AnyValue.hs
- src/Toml/Type/Value.hs
- test/Test/Toml/Gen.hs
Resolves [#87](https://github.com/kowainik/tomland/issues/87)
> [#87] Improve double generator

- CHANGELOG.md
- examples/Playground.hs
- src/Toml/Bi/Code.hs
- src/Toml/Bi/Combinators.hs
- src/Toml/Bi/Monad.hs
> [#81] Perform data type renaming

- CHANGELOG.md
- src/Toml/Parser.hs
- stack.yaml
- tomland.cabal
> [#90] Migrate to megaparsec 7

- CHANGELOG.md
- src/Toml/BiMap.hs
This is to address #70.
Maybe the class definition should move to `AnyValue.hs`.
This is my first time sending a PR to a project like this one, I hope I can contribute.
> [Issue #70] Added function to create BiMap from concrete types

- CHANGELOG.md
- src/Toml/Bi/Code.hs
Resolves [#109](https://github.com/kowainik/tomland/issues/109)
> [#109] Add `decodeToml` function

- CHANGELOG.md
- benchmark/Benchmark/Type.hs
- benchmark/Main.hs
- benchmark/benchmark.toml
- src/Toml/Bi/Monad.hs
- src/Toml/Parser/TOML.hs
- src/Toml/Parser/Value.hs
- test/Test/Toml/Parsing/Unit.hs
- tomland.cabal
Resolves #14 
I am fairly jet-lagged at the moment so this should probably be considered work in progress, especially since I have not tested the parser very extensively yet.
> [#14] Parsing inline tables

- .travis.yml
- CHANGELOG.md
- stack.yaml
- tomland.cabal
Let me know if I missed something.
> Prepare for 0.5.0 release

- CHANGELOG.md
- src/Toml/Edsl.hs
Resolves #133 
using [stylish-haskell.yaml][stylish] file in the repository.
Start the first line of the commit with the issue number in square parentheses.
> [#133] Patching EDSL for arrays of tables

- CHANGELOG.md
- examples/Playground.hs
- src/Toml/PrefixTree.hs
> [#149] Removing record syntax from PrefixTree

- CHANGELOG.md
- src/Toml/Bi/Combinators.hs
> [#152] Remove mdimap

- CHANGELOG.md
- src/Toml/Bi/Code.hs
- src/Toml/Bi/Combinators.hs
- src/Toml/BiMap.hs
- src/Toml/Type/AnyValue.hs
- src/Toml/Type/Value.hs
- test/Test/Toml/Gen.hs
Resolves [#137](https://github.com/kowainik/tomland/issues/137)
Next task:
> [#137] Replace Maybe with Either in BiMap

- CHANGELOG.md
- src/Toml/Parser/Value.hs
- src/Toml/Printer.hs
- test/Test/Toml/PrefixTree/Property.hs
- test/Test/Toml/Printer/Golden.hs
- test/golden/pretty_default.golden
- test/golden/pretty_indented_only.golden
- test/golden/pretty_sorted_only.golden
- test/golden/pretty_unformatted.golden
>  [#134] Pretty printer for table arrays

- CHANGELOG.md
- src/Toml/Bi/Map.hs
- test/Test/Toml/BiMap/Property.hs
- test/Test/Toml/Gen.hs
- tomland.cabal
Resolves #119.
It's almost my first time playing with properties in hedgehog, let me know if I'm missing something.
I don't know how to test lazy bytestrings.
> [#119] Add property-based tests for BiMap

- CHANGELOG.md
- src/Toml/Parser/TOML.hs
- src/Toml/Parser/Value.hs
- src/Toml/PrefixTree.hs
- test/Test/Toml/Gen.hs
- test/Test/Toml/Parsing/Unit.hs
Resolves #143 
Resolves #162 
This is a fairly big one... 
- I should add it to `CHANGELOG`
- I should add a whole bunch of tests, I've only tested it on simple cases so far
- I had to change a whole bunch of files since the definition of `TOML` was expanded, including printing functions
- The way I test the subtables in `tableArrayP` is kind of experimental, there might be a better way
> [#143] Parser for array of tables

- CHANGELOG.md
- src/Toml/Parser/TOML.hs
- test/Test/Toml/Gen.hs
- test/Test/Toml/Parsing/Unit.hs
Resolves #144 
Works as expected.
> [#144] Added tests for Arrays of Tables

- examples/Playground.hs
- src/Toml/Bi/Map.hs
- src/Toml/Parser/Value.hs
- src/Toml/Printer.hs
- src/Toml/Type/AnyValue.hs
- src/Toml/Type/UValue.hs
- src/Toml/Type/Value.hs
- test/Test/Toml/Gen.hs
- test/Test/Toml/Parsing/Unit.hs
Note that parsing should be improved to make it more correct.
Also, I didn't updated the Changelog yet, should I do that?
Resolves #163 ?
> [#163] Move dates from DateTime

- examples/Playground.hs
- examples/biTest.toml
- src/Toml/Bi.hs
- src/Toml/Bi/Combinators.hs
- src/Toml/Bi/Monad.hs
Resolves #13 
Resolves #155 
See `examples/Playground.hs` on how you can now use lists of custom types.
> [#155] Implement 'list' combinator (and improve docs)

- src/Toml/Parser.hs
- src/Toml/Parser/Core.hs
- src/Toml/Parser/String.hs
- src/Toml/Parser/TOML.hs
- src/Toml/Parser/Value.hs
- test/Test/Toml/Parsing/Unit.hs
- tomland.cabal
> Refactor parsing modules

- src/Toml.hs
- src/Toml/Bi/Code.hs
- src/Toml/Bi/Combinators.hs
- src/Toml/Bi/Map.hs
- src/Toml/Bi/Monad.hs
- src/Toml/Edsl.hs
- src/Toml/Parser.hs
- src/Toml/PrefixTree.hs
- src/Toml/Printer.hs
- src/Toml/Type.hs
- src/Toml/Type/AnyValue.hs
- src/Toml/Type/TOML.hs
- src/Toml/Type/UValue.hs
- src/Toml/Type/Value.hs
- tomland.cabal
Just writing great documentation in general :slightly_smiling_face:
> Improve all documentation for tomland and fix all Haddock warnings

- CHANGELOG.md
- README.md
- src/Toml.hs
- src/Toml/Bi/Code.hs
- tomland.cabal
* Patch changelog
* Add links to blog post
* Add icon
* Minor fixes
> Prepare for 1.0.0 release

- .travis.yml
- CHANGELOG.md
- README.md
- stack.yaml
- test/Test/Toml/Gen.hs
- tomland.cabal
> [#187] Bump up hedgehog to 1.0

- src/Toml/Printer.hs
- test/Test/Toml/Printer/Golden.hs
- test/golden/pretty_custom_sorted.golden
@chshersh As discussed, this code does not yet compile, but I'm opening this PR to facilitate discussion. Thanks!
> [#189] Implement custom table key sorting

- stack.yaml
- tomland.cabal
> [#194] Fix CI

- .travis.yml
- CHANGELOG.md
- README.md
- benchmark/Benchmark/Htoml.hs
- benchmark/Benchmark/HtomlMegaparsec.hs
- benchmark/Benchmark/TomlParser.hs
- benchmark/Benchmark/Tomland.hs
- benchmark/Benchmark/Type.hs
- cabal.project
- examples/Playground.hs
- src/Toml/Bi/Code.hs
- src/Toml/Bi/Map.hs
- src/Toml/Parser/Key.hs
- src/Toml/PrefixTree.hs
- src/Toml/Printer.hs
- src/Toml/Type/AnyValue.hs
- src/Toml/Type/TOML.hs
- src/Toml/Type/UValue.hs
- src/Toml/Type/Value.hs
- stack.yaml
- test/Test/Toml/BiCode/Property.hs
- tomland.cabal
Resolves #213
Currently blocked by https://github.com/haskell-infra/hackage-trustees/issues/238
> [#213] Support GHC-8.8

- README.md
- examples/Playground.hs
- src/Toml/Bi/Combinators.hs
- src/Toml/Generic.hs
- tomland.cabal
Implements #201 
Signed-off-by: Sanchayan Maity <maitysanchayan@gmail.com>
> Add combinators set and hashSet for array of tables

- src/Toml/Bi/Combinators.hs
- src/Toml/Bi/Map.hs
- src/Toml/Generic.hs
- test/Test/Toml/BiMap/Property.hs
- test/Test/Toml/Gen.hs
> [#204] Add _ByteStringArray bimap

- README.md
- examples/Playground.hs
- examples/biTest.toml
- src/Toml/Bi/Monad.hs
Fixes #226 
Hope the example is sensible enough. And if some more documentation should be added, do tell. :)
> [#226] Add dimatch combinator for sum types

- .github/workflows/build.yml
- .github/workflows/test.yml
- .gitignore
- README.md
- default.nix
> Add GitHub Actions using cachix

- CHANGELOG.md
- src/Toml/Bi/Combinators.hs
- src/Toml/Bi/Map.hs
- src/Toml/Bi/Monad.hs
- src/Toml/Generic.hs
- src/Toml/Parser/Item.hs
- src/Toml/Parser/Key.hs
- src/Toml/Parser/Validate.hs
- stack.yaml
* Changelog updated
* Added `@since` annotations
* Documentation is fixed in some places
* Updated to the latest LTS snapshot
> Prepare for 1.2.0.0 release

- .github/CODEOWNERS
- src/Toml.hs
- src/Toml/Bi.hs
- src/Toml/Bi/Code.hs
- src/Toml/Bi/Combinators.hs
- src/Toml/Bi/Map.hs
- src/Toml/Bi/Monad.hs
- src/Toml/Edsl.hs
- src/Toml/Generic.hs
- src/Toml/Parser.hs
- src/Toml/Parser/Core.hs
- src/Toml/Parser/Item.hs
- src/Toml/Parser/Key.hs
- src/Toml/Parser/String.hs
- src/Toml/Parser/Validate.hs
- src/Toml/Parser/Value.hs
- src/Toml/PrefixTree.hs
- src/Toml/Printer.hs
- src/Toml/Type.hs
- src/Toml/Type/AnyValue.hs
- src/Toml/Type/TOML.hs
- src/Toml/Type/UValue.hs
- src/Toml/Type/Value.hs
* Add CODEOWNERS
* Specify Haddock per-module metadata
Looks much better now!
**Before**
**After**
> Update OSS maintenance info

- CHANGELOG.md
- src/Toml/Bi/Combinators.hs
- test/Test/Toml/BiCode/Property.hs
Resolves #241
I think that iit probably should be a major version update as the name clash could harm when updating...
> [#241] Implement codecs for some common Monoid types

- examples/Main.hs
- examples/biTest.toml
- src/Toml/Bi/Combinators.hs
- src/Toml/Bi/Map.hs
- src/Toml/PrefixTree.hs
Implement `tableMapCodec` and necessary supporting functions as outlined in #254. Includes `TomlBiMap`s from Key to Text and String.
> Dynamic keys

- .gitignore
- src/Toml/Parser/Item.hs
- stack.yaml
- test/Spec.hs
- test/Test/Toml/BiCode/Property.hs
- test/Test/Toml/BiMap/Property.hs
- test/Test/Toml/Gen.hs
- test/Test/Toml/Parsing/Examples.hs
- test/Test/Toml/Parsing/Property.hs
- test/Test/Toml/Parsing/Unit.hs
- test/Test/Toml/Parsing/Unit/Array.hs
- test/Test/Toml/Parsing/Unit/Bool.hs
- test/Test/Toml/Parsing/Unit/Common.hs
- test/Test/Toml/Parsing/Unit/Date.hs
- test/Test/Toml/Parsing/Unit/Double.hs
- test/Test/Toml/Parsing/Unit/Integer.hs
- test/Test/Toml/Parsing/Unit/Key.hs
- test/Test/Toml/Parsing/Unit/Text.hs
- test/Test/Toml/Parsing/Unit/Toml.hs
- test/Test/Toml/PrefixTree/Property.hs
- test/Test/Toml/PrefixTree/Unit.hs
- test/Test/Toml/Printer/Golden.hs
- test/Test/Toml/Property.hs
- test/Test/Toml/TOML/Property.hs
- tomland.cabal
> [#252] Switch testing from 'tasty-*' libraries to 'hspec-*' libraries

- CHANGELOG.md
- src/Toml/Parser/Validate.hs
- test/Spec.hs
- test/Test/Toml/Parsing/Validation.hs
- tomland.cabal
> [#218] Implement tests for TOML validation

- CHANGELOG.md
- examples/Main.hs
- examples/biTest.toml
- src/Toml/Codec/Combinators.hs
Resolves #261
@vrom911 and I brainstormed the solution for this problem and came up with a nice implementation. I'm quite happy that we could avoid full-batteries TOML codec running. @everythingfunctional you can check it out, it should address your use case that you've attempted to solve in #262.
> [#261] Table MapsCodec

- CHANGELOG.md
- examples/Main.hs
- examples/biTest.toml
- src/Toml/Codec/BiMap.hs
- src/Toml/Codec/Combinators.hs
- src/Toml/Codec/Di.hs
> [#270] Implement codecs for pair and triple

- CHANGELOG.md
- examples/Main.hs
- examples/biTest.toml
- src/Toml/Codec/BiMap/Conversion.hs
- src/Toml/Codec/Combinator.hs
- src/Toml/Codec/Combinator/Custom.hs
> [#237] Combinator with predicate

- test/Test/Toml/BigType.hs
- test/Test/Toml/Codec/Combinator.hs
- test/Test/Toml/Codec/Combinator/Common.hs
- test/Test/Toml/Codec/Combinator/Primitive.hs
- tomland.cabal
> [#280] Roundtrip tests for Combinator.Primitive

- src/Toml/Codec/Combinator/Common.hs
- src/Toml/Codec/Combinator/Monoid.hs
- src/Toml/Codec/Combinator/Time.hs
- src/Toml/Codec/Combinator/Tuple.hs
Part of #283 
I wrote a few sentences, but it's going tough for me...
> [#283] A few top-level sentences

- .github/workflows/ci.yml
- test/Spec.hs
- test/Test/Toml/Codec.hs
- test/Test/Toml/Codec/BiMap.hs
- test/Test/Toml/Codec/BiMap/Conversion.hs
- test/Test/Toml/Codec/Combinator.hs
- test/Test/Toml/Codec/Combinator/List.hs
- test/Test/Toml/Codec/Combinator/Map.hs
- test/Test/Toml/Codec/Combinator/Primitive.hs
- test/Test/Toml/Codec/Combinator/Set.hs
- test/Test/Toml/Codec/Combinator/Tuple.hs
- test/Test/Toml/Codec/Generic.hs
- test/Test/Toml/Type.hs
- test/Test/Toml/Type/PrefixTree.hs
- test/Test/Toml/Type/TOML.hs
Resolves #297
Now tests take 8 seconds instead of 25 on my local machine.
Also, speed up CI.
> [#297] Speed up tests

- CHANGELOG.md
- src/Toml/Codec/BiMap/Conversion.hs
- test/Test/Toml/Codec/BiMap/Conversion.hs
- test/Test/Toml/Codec/Combinator/Common.hs
Resolves #289
Thanks for the clear description of the issue and tests improvement instructions, @chshersh :purple_heart:
> [#289] Implement `_Coerce :: TomlBiMap`

- src/Toml/Codec/BiMap.hs
- src/Toml/Codec/BiMap/Conversion.hs
- src/Toml/Codec/Code.hs
- src/Toml/Codec/Combinator/Common.hs
- src/Toml/Codec/Combinator/Custom.hs
- src/Toml/Codec/Combinator/List.hs
- src/Toml/Codec/Combinator/Primitive.hs
- src/Toml/Codec/Combinator/Set.hs
- src/Toml/Codec/Combinator/Table.hs
- src/Toml/Codec/Combinator/Time.hs
- src/Toml/Codec/Di.hs
- src/Toml/Codec/Error.hs
- src/Toml/Codec/Generic.hs
- src/Toml/Codec/Types.hs
- src/Toml/Parser.hs
- src/Toml/Type/AnyValue.hs
- src/Toml/Type/Edsl.hs
- src/Toml/Type/Key.hs
- src/Toml/Type/PrefixTree.hs
- src/Toml/Type/Printer.hs
- src/Toml/Type/TOML.hs
- src/Toml/Type/UValue.hs
- src/Toml/Type/Value.hs
- test/Test/Toml/Codec/Combinator/Map.hs
Resolves #273
That was an interesting history lesson :slightly_smiling_face: 
Also:
* Refactored `Generic` codecs, added INLINE pragmas
* Fixed some `@since` annotations
> [#273] Add @since annotations to each function and module

- CHANGELOG.md
- src/Toml/Codec/BiMap/Conversion.hs
- src/Toml/Codec/Combinator.hs
- src/Toml/Codec/Combinator/Map.hs
- test/Test/Toml/Codec/BiMap/Conversion.hs
> [#243] Support more `Map`-like data structures

- CHANGELOG.md
- examples/Main.hs
- examples/biTest.toml
- src/Toml/Codec/Combinator.hs
- src/Toml/Codec/Combinator/List.hs
- src/Toml/Codec/Combinator/Map.hs
- src/Toml/Codec/Combinator/Set.hs
- src/Toml/Codec/Combinator/Table.hs
- src/Toml/Codec/Error.hs
- test/Test/Toml/Codec/Combinator/Set.hs
> [#283] Docs for codecs

- CHANGELOG.md
- src/Toml/Codec/Generic.hs
> [#242] Implement `Generic` codecs for `Map`

- CHANGELOG.md
- src/Toml/Codec/Generic.hs
- test/Test/Toml/Codec/SmallType.hs
> [#251] Add 'ByteString' newtypes for Generic coding

- CHANGELOG.md
- src/Toml/Codec/Combinator/List.hs
- src/Toml/Codec/Combinator/Table.hs
- src/Toml/Codec/Error.hs
> [#302] Distinguish TableNotFound and TableArrayNotFound

- examples/Main.hs
- src/Toml/Codec/Code.hs
- src/Toml/Codec/Combinator/Common.hs
- src/Toml/Codec/Combinator/List.hs
- src/Toml/Codec/Combinator/Map.hs
- src/Toml/Codec/Combinator/Table.hs
- src/Toml/Codec/Di.hs
- src/Toml/Codec/Error.hs
- src/Toml/Codec/Types.hs
- stack.yaml
- tomland.cabal
> [#271] Use 'Validation' from 'validation-selective' in 'TomlEnv'

- CHANGELOG.md
- src/Toml/Codec/Combinator/Table.hs
- src/Toml/Codec/Error.hs
- test/Test/Toml/Codec.hs
- test/Test/Toml/Codec/Code.hs
- tomland.cabal
> [#310] Add tests on `TomlDecodeError`s

- CHANGELOG.md
- src/Toml/Codec/Combinator/Common.hs
- src/Toml/Codec/Combinator/Map.hs
- src/Toml/Codec/Error.hs
- test/Test/Toml/Codec/Code.hs
> [#313] Put 'Key' to 'BiMapError'

- src/Toml.hs
- src/Toml/Codec.hs
Added a few sentences to help use the library.
> Top-level description for 'Toml.Codec'

- CHANGELOG.md
- src/Toml/Codec/BiMap/Conversion.hs
- src/Toml/Parser.hs
- test/Test/Toml/Parser/Key.hs
- test/Test/Toml/Type/Key.hs
> [#318] Fix roundtrip test for Key

- CHANGELOG.md
- examples/Main.hs
- examples/generic.toml
- src/Toml/Codec/Generic.hs
- tomland.cabal
Resolves #272
Thanks a lot, @chshersh for such a great job on this already! I just needed to test it and it all worked :mage:
> [#272] DerivingVia for Generic table codecs

- CHANGELOG.md
- examples/Main.hs
- examples/biTest.toml
- src/Toml/Codec/Combinator/Map.hs
- test/Test/Toml/Codec/Combinator/Map.hs
> [#335] tableMap codec with list value is irreversible

- .github/workflows/ci.yml
- CHANGELOG.md
- appveyor.yml
- stack.yaml
- test/Test/Toml/Parser/Common.hs
- tomland.cabal
> [#338] Upgrade to `megaparsec-9.0.0.0`

- .github/dependabot.yml
- .github/workflows/ci.yml
> [#340] Add dependabot

- CHANGELOG.md
- tomland.cabal
> [#358] Update parser-combinators bounds

- CHANGELOG.md
- examples/Main.hs
- examples/biTest.toml
- src/Toml/Codec/BiMap/Conversion.hs
- src/Toml/Codec/Combinator/Common.hs
- src/Toml/Codec/Combinator/Custom.hs
- test/Test/Toml/Codec/BiMap/Conversion.hs
- test/Test/Toml/Codec/Code.hs
- test/Test/Toml/Codec/Combinator/Custom.hs
> [#329] Add _Hardcoded `TomlBiMap`

- examples/Main.hs
- examples/generic.toml
- src/Toml/Codec/Generic.hs
> [#322] Strip Prefix with DerivingVia TomlTable

- .github/workflows/ci.yml
- CHANGELOG.md
- tomland.cabal
> [#370] Support GHC-9.0

- tomland.cabal
> Allow hspec 2.8

- test/Test/Toml/Gen.hs
Fixes #374 
`quotedWith` now takes in an additional parameter- `isAllowed`. It's now the caller's responsibility to indicate which characters are allowed within the string generated by `quotedWith` (the delimiter check is still done by `quotedWith`).
For basic strings (double quote), control characters, as well as backslashes are disallowed.
For literal strings (single quote), only control characters are disallowed.
> Fix `genPiece` generating basic string with raw backslash within

- .github/workflows/ci.yml
- CHANGELOG.md
- tomland.cabal
Mostly maintenance updates so people who depend on `tomland` could build their documentation.
I've also updated the upper bounds for multiple dependencies.
> Prepare 1.3.3.1 release

- .github/workflows/ci.yml
- CHANGELOG.md
- tomland.cabal
> [#395] Support GHC-9.2

- tomland.cabal
Builds fine and all tests pass.
> Allow megaparsec 9.3
